# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4yFhA0pfv3qy-kbG11JmG0c0aotQ2I0
"""

!pip install streamlit
import streamlit as st
import pickle
import numpy as np

# Load the saved model
with open('best_model.joblib', 'rb') as file:
    model = pickle.load(file)

# Title and description
st.title("Customer Churn Prediction")
st.write("Enter customer details to predict churn.")

# Input fields for user to provide customer data
age = st.number_input("Age", min_value=0, max_value=120, step=1, value=30)
total_purchase = st.number_input("Total Purchase", min_value=0.0, step=0.1, value=5000.0)
account_manager = st.selectbox("Account Manager Assigned?", [0, 1], format_func=lambda x: "Yes" if x == 1 else "No")
years = st.number_input("Years with the Company", min_value=0.0, step=0.1, value=3.0)
num_sites = st.number_input("Number of Sites", min_value=0, step=1, value=5)

# Button to make predictions
if st.button("Predict"):
    # Prepare input features
    input_features = np.array([[age, total_purchase, account_manager, years, num_sites]])

    # Make prediction
    prediction = model.predict(input_features)[0]

    # Display result
    if prediction == 1:
        st.error("The customer is likely to churn.")
    else:
        st.success("The customer is unlikely to churn.")